//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaktimarg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapMenuToRole
    {
        public byte RoleId { get; set; }
        public int MenuId { get; set; }
        public bool AllowCreate { get; set; }
        public bool AllowUpdate { get; set; }
        public bool AllowDelete { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
